### ISSUE TITLE
EP 4. 김조한 (김환을 위한 조명을 한번 쯤 만들 때가 되었다)

### ISSUE THREAD

**Issue by zommeworks** [zommeworks/topbobdle#25]
하고 싶은 것
일출 시간 30분 전부터 dimming 하는 조명을 만들고 싶다
+ 음성 또는 앱으로 제어하고 싶다
+ led 애니메이션 을 만들고 싶다

목표는 딱 그거다
* Neopixel + raspberry Pi + google assistant
* 외장 데코용 목공 (+ 쇠 가공)

### subtask
- [x] raspberry pi + neopixel 테스트
- [x] raspberry pi + google assistant 연동 방법 공부
- [x] google assistant sdk 사용방법 숙지
- [x] integration test
- [ ] 본 프로그램 코딩
- [ ] 외형 설계 (어떻게 만들 것인지 같이 생각했으면 좋겠다)
- [ ] 회로 설계
- [ ] 납땜 및 전선 wrapping
- [ ] PI ENCLOSER (박스)
- [ ] 기타등등

### DRI
나중에 다시 논의

### schedule
2주 뒤 시작

1. 알아놓을 것 다 알아놓기
1. 설계 
1. 실질적인 제작
1. 설치 및 테스트. 김조한 노래 부르기

파티 세레모니는 어떻게 할 것인가
(김환 집 옥상 전기 들어오는지 확인)
* 게 나왔습니다
* 랍스터
* 이베리코
* (크래미 > 새우 > 대게 > 랍스터)

### note
* MVP는 애니메이션이 아니라 구글 홈과 연동하여 켜고 끄는 것이다
* mvp를 만들고 김환이 만지작 할 수 있도록 세팅하는 것이 필요하다
